/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const removeAccountPopover: string;
declare const buttons: string;
declare const yes: string;

export {
	buttons,
	yes
};

declare const __default_export__: {
	"remove-account-popover": typeof removeAccountPopover;
	buttons: typeof buttons;
	yes: typeof yes;
};
export default __default_export__;
