/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const content: string;
declare const twoColumns: string;
declare const sameWidth: string;

export {
	content
};

declare const __default_export__: {
	content: typeof content;
	"two-columns": typeof twoColumns;
	"same-width": typeof sameWidth;
};
export default __default_export__;
