/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const loginForm: string;

declare const __default_export__: {
	"login-form": typeof loginForm;
};
export default __default_export__;
