/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const dialog: string;
declare const content: string;

export {
	dialog,
	content
};

declare const __default_export__: {
	dialog: typeof dialog;
	content: typeof content;
};
export default __default_export__;
