/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const dailyNote: string;
declare const topBar: string;
declare const dateLabel: string;
declare const noteContent: string;

declare const __default_export__: {
	"daily-note": typeof dailyNote;
	"top-bar": typeof topBar;
	"date-label": typeof dateLabel;
	"note-content": typeof noteContent;
};
export default __default_export__;
