/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const sliders: string;

export {
	sliders
};

declare const __default_export__: {
	sliders: typeof sliders;
};
export default __default_export__;
